/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Takuya (https://sketchfab.com/craftzdog)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/voxel-dog-7604c96da44a44ba900c51e753fb6339
title: Voxel Dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/new7.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.01, -0.01]} rotation={[-1.57, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[3.69, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.palette} />
          </group>
          <group position={[-3.4, 0, -2.95]} scale={[7.05, 1, 7.05]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/new7.gltf')
